### ISSUE TITLE
Software Breakpoint

### ISSUE THREAD

**Issue by sriharich20** [pulp-platform/riscv-dbg#121]
Can some one explain how ebreak instruction will be replaced in the breakpoint address by GDB. Wheter ebreak is written to breakpoint address by using system bus access (SBA) or using program buffer?

**Comment by bluewww** [comment]
I think this depends on the software stack you are using. Both ways are possible.

**Comment by sriharich20** [comment]
In this implementation how ebreak is replaced at software breakpoints

**Comment by sriharich20** [comment]
> I think this depends on the debug software you are using. Both ways are possible.

if the ebreak instruction is replaced by debugger configuring the program buffer then hart has to execute the program buffer which contains the instruction writing ebreak to the instruction memory is that possible
