### ISSUE TITLE
[Question]: OpenOCD Compliance Support

### ISSUE THREAD

**Issue by sajjadahmed677** [pulp-platform/riscv-dbg#148]
Hi all,

There is support for running OpenOCD compliance for RISCV debug. I have tried running it and it's working with current commit of the debug module. But according to the following [discussion](https://github.com/riscv/riscv-openocd/issues/462#issuecomment-606138313) OpenOCD compliance were deprecated. is it true or we still have support for OpenOCD compliance?

**Comment by bluewww** [comment]
It was deprecated but we are still running the tests.
