### ISSUE TITLE
`sberror` not clearing properly causes OpenOCD interoperability issues

### ISSUE THREAD

**Issue by timothytrippel** [pulp-platform/riscv-dbg#154]
The OpenTitan project uses GDB/OpenOCD to develop top-level debug and manufacturing test cases. We have noticed some test failures when performing unaligned system bus accesses (see [here](https://github.com/lowRISC/opentitan/issues/17729#issuecomment-1488923308)).

In short, when an unaligned read operation is performed, `sberror` is set to 3 (which is correct according to the spec), but after, OpenOCD tries to clear the error with a W1C, by sending 0x7, however, the `sberror` field fails to clear. We believe there is an RTL bug described [here](https://github.com/lowRISC/opentitan/issues/17729#issuecomment-1489076212).

Could someone confirm / fix?

**Comment by bluewww** [comment]
I agree with @andreaskurth interpretation of the spec. I would opt for the backwards compatible solution because we might already rely on this behavior in some testbench (assuming the meaning of `undefined` is the same as in e.g. the C programming language standard)

**Comment by andreaskurth** [comment]
Thanks for your feedback, @bluewww. :+1:

I did not find a definition of _undefined_ in the RISC-V Debug Spec, and other RISC-V specs I know use _implementation-defined_ instead. But I think interpreting _undefined_ as _implementation-defined_ for the Debug Spec, too, makes sense.

I'll create a PR to implement the backwards-compatible solution
