### ISSUE TITLE
cmderr=0 when accessing data0 while busy

### ISSUE THREAD

**Issue by suppamax** [pulp-platform/riscv-dbg#37]
Hi,

as you can see from the attached waveform
![Screenshot from 2019-09-13 13-36-42](https://user-images.githubusercontent.com/25659164/66300764-2d3bbf80-e8f6-11e9-9490-5413a682afdf.png)
there is an attemped data write while the previous command (another data write) was still ongoing, and there is no cmderr flagging the conflict as per specs (paragraph 3.1211)
`Accessing these registers while an abstract command is executing causes cmderr to be set to 1 (busy) if it is 0.`

**Comment by noytzach** [comment]
Pull request #79 should solve this issue
