### ISSUE TITLE
Missing patch from Arianne?

### ISSUE THREAD

**Issue by imphil** [pulp-platform/riscv-dbg#4]
Am I correct that https://github.com/pulp-platform/ariane/pull/180 ("Fix register access issue in debug mode, only affects A0") should go into this repo as well? (I'll open a PR then.)

**Comment by zarubaf** [comment]
I think the patch has been ported by @bluewww on his pulpissimo branch: https://github.com/pulp-platform/riscv-dbg/commit/ad12987af53681582669cdf53265614e58177fc4

We might want to cherry-pick this to master? Thoughts?

**Comment by imphil** [comment]
Ah bad timing, I see this patch in the pulpissimo_integration branch as well. Sorry for the noise.
