### ISSUE TITLE
Looking for getting started with riscv-dbg

### ISSUE THREAD

**Issue by AntonBabushkin** [pulp-platform/riscv-dbg#47]
Hi, 
I'd like to play with this great project.
However I am lacking a getting started info.
Could you please point me to any example of a test bench integrating **riscv-dbg** together with a core and running some simulations with it.
Please excuse me if I've simply overlooked what I am asking for, your help is highly appreciated.
Thanks.

**Comment by bluewww** [comment]
[This](https://github.com/openhwgroup/cv32e40p/tree/master/tb/dm) testbench runs `RI5CY` and this debug module.

**Comment by AntonBabushkin** [comment]
Hi @bluewww , thank you so much for pointing me to it!
